print("=" * 40)
print("Student Registration")
print("=" * 40)
student_name=input("Enter Student Name: ")
student_age=int(input("Enter Student Age: "))
sudent_city=input("Enter Student City: ")
student_course=input("Enter Student Course: ")
print("Student Name: ",student_name)
print("Student Age: ",student_age)
print("Studnet City: ",sudent_city)
print("Student Course:",student_course)
print("=" * 40)
print("Registration Successful!")
print("=" * 40)